config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :questions do
    resources :answers, only: [:create] do
      resources :reviews, only: %i[new create]
      resources :payments, only: %i[new create]
    end
    resources :answers, only: %i[new create show update]
  end
  resources :answers, only: %i[index edit destroy]

  resources :payments, except: [:new, :create]


  post "answers/:id/paid", to: "answers#paid", as: :paid
  get "/questions_lawyers", to: "questions#general", as: :preguntas
  get "answers/:id/response", to: "answers#after_paid", as: :response
  get "answers/:id/choosed", to: "answers#choosed", as: :choosed
  post "answers/:id/procesar-pago", to: "answers#check_payment", as: :check_payment
  #get "pago", to: "answers#pago", as: :pago
  post "process_payment", to: "payments#process_payment"

  resources :users, only: %i[show edit update] do
    resources :studies, only: %i[create update destroy]
    resources :experiences, only: %i[create update destroy]
  end

  get '/404', to: 'errors#not_found'
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers

  scope :find_all_questions, -> { order("created_at DESC") }

  include PgSearch::Model
  pg_search_scope :search_by_category,
    against: [ :category ],
    using: {
      tsearch: { prefix: true }
    }

  # Validates
  validates :title, :description, :category, :status, :user, presence: true

  include AASM

  aasm_column :status
  aasm do
    state :waiting, initial: true
    state :choosing, :paid, :answered, :ended, :discarted

    event :new_answer do
      transitions from: :waiting, to: :choosing
    end

    event :choosed do # Choosed and get paid
      transitions from: :choosing, to: :paid
    end

    event :answer_delivered do # With attachment
      transitions from: :paid, to: :answered
    end

    event :finalize do # Leave with review
      transitions from: :answered, to: :ended
    end

    event :discard do # Rejected
      transitions from: [:waiting, :choosing], to: :discarted
    end
  end
  # waiting, con_respuestas, pagada, respondida, terminada
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[show edit update destroy]

  def index
    @questions = Question.find_all_questions
    @question = Question.new
  end

  def general
    if params[:query].present?
      @questions = Question.search_by_category(params[:query])
    else
      @questions = Question.find_all_questions
    end
  end

  def new
    @question = Question.new
  end

  def create
    @user = User.find(current_user.id)
    @question = Question.new(question_params)
    @question.user = current_user

    if @question.save
      redirect_to question_path(@question)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show

  end

  def edit
  end

  def update
    if @question.update(question_params)
      redirect_to question_path(@question)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_path, status: :see_other
  end

  private

  def question_params
    params.require(:question).permit(:title, :description, :category)
  end

  def set_question
    @question = Question.find(params[:id])
  end
end

app/views/questions/_form.html.erb
<%= simple_form_for @question do |f| %>
  <%= f.input :title, label: "Pregunta", required: true%>
  <%= f.input :description, label: "Descripción", required: true %>
  <%# <%= f.input :category, label: "Categoría", required: true %>
  <%= f.collection_select :category, Category.all, :id, :name, {prompt: "Selecciona una categoría"}, {class: "form-control", required: true} %>
  <%= f.button :submit, class: "btn btn-flat", value:"Publicar pregunta" %>
<% end %>

app/views/questions/_review_form.html.erb
<%= form_with(url: questions_path, method: :post, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :rating %>
    <%= form.select :rating, (1..5).to_a, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :comment %>
    <%= form.text_area :comment, class: 'form-control' %>
  </div>
  <%= form.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

app/views/questions/create.html.erb
<h1>Questions#create</h1>
<p>Find me in app/views/questions/create.html.erb</p>

app/views/questions/destroy.html.erb
<h1>Questions#destroy</h1>
<p>Find me in app/views/questions/destroy.html.erb</p>

app/views/questions/edit.html.erb
<h1>Questions#edit</h1>
<p>Find me in app/views/questions/edit.html.erb</p>

<div class="container">
  <h1>Edita tu pregunta:</h1>
  <div class="row">
    <div class="col-3"></div>

    <div class="col-6 border border-dark p-3 mb-3">
      <%= render "form" %>
    </div>
    <p></p>
    <div class="col-3"></div>
  </div>

</div>

app/views/questions/general.html.erb
<% if current_user.lawyer? %>
<div class="container-h1 mt-3">
    <h1>Preguntas disponibles:</h1>
</div>

<hr>

<div class="container-h1 mt-3">
  <div class="btn-group">
    <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
      Filtrar Categoria
    </button>
    <ul class="dropdown-menu">
      <li class="list-unstyled"><%= link_to "Impuestos", "/questions_lawyers?query=Impuestos", class:"text-decoration-none", style: "color: black" %></li>
      <li class="list-unstyled"><%= link_to "Leyes", "/questions_lawyers?query=Leyes", class:"text-decoration-none", style: "color: black" %></li>
      <li class="list-unstyled"><%= link_to "Empresas", "/questions_lawyers?query=Empresas", class:"text-decoration-none", style: "color: black" %></li>
      <li class="list-unstyled"><%= link_to "Personas", "/questions_lawyers?query=Personas", class:"text-decoration-none", style: "color: black" %></li>
    </ul>
  </div>
</div>

<div class="container-md">
  <div class="accordion accordion-flush" id="accordionFlushExample">
    <% @questions.each do |question| %>
      <div class="accordion-item">
        <h2 class="accordion-header" id="flush-heading<%= question.id %>">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse<%= question.id %>" aria-expanded="false" aria-controls="flush-collapse<%= question.id %>">
            <%= question.title %>
          </button>
        </h2>
        <div id="flush-collapse<%= question.id %>" class="accordion-collapse collapse" aria-labelledby="flush-heading<%= question.id %>" data-bs-parent="#accordionFlushExample">
          <div class="accordion-body"> <%= question.description %>
            <p></p>
            <%= button_to "Responder", new_question_answer_path(question), method: :get, class:"button-81" %>
            <p></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<% else %>
  <div class="h-100 d-flex align-items-center justify-content-center opacity-75" style="margin-top: 20px;">
    <br>
    <h2> Esta sección es solo para abogados verificados </h2>
  </div>

  <div class="h-100 d-flex align-items-center justify-content-center" style="margin-top: 10px; ">
    <%= button_to "Volver", questions_path, method: :get, class:"button-81" %>
  </div>
<% end %>

<!--
  <div class="row mt-5">
    <% @questions.each do |question| %>
      <div class="col-12 mb-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= question.title %></h5>
            <p class="card-text"><%= question.description %></p>
            <% # aqui hay que ver como expandir la card para que se vea toda la info y poner %>
            <% # modal al final de esa expansion para poder responder %>
            <%#= link_to 'View details', question_answer_path(answer.question, answer), class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
-->

app/views/questions/index.html.erb
<div class="container-h1 mt-3">
  <h1>Mis preguntas</h1>
</div>
<hr>

<div class="container mt-3">
  <button type="button" class="button-79"  data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@mdo" data-controller="modal" data-action="click->modal#openModal">Nueva Pregunta</button>

  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Haz tu pregunta</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <%# <div class="mb-3">
              <label for="recipient-name" class="col-form-label">Pregunta:</label>
              <input type="text" class="form-control" id="recipient-name">
            </div>
            <div class="mb-3">
              <label for="message-text" class="col-form-label">Contexto:</label>
              <textarea class="form-control" id="message-text"></textarea>
            </div> %>
          <%# </form> %>
          <form class="simple_form new_question" id="new_question" novalidate="novalidate" action="/questions" accept-charset="UTF-8" method="post"><input type="hidden" name="authenticity_token" value="Xqqv2tmlIS8UdrnikZvjN-zry_0DpGCjSS4OhT9JoZkJwIa-iHW3IwaAbwbYZe8bjY0OyjrRSx0QiK3eS4y2SQ" autocomplete="off">
            <div class="mb-3 string required question_title"><label class="form-label string required" for="question_title">Pregunta <abbr title="required">*</abbr></label><input class="form-control string required" required="required" aria-required="true" type="text" name="question[title]" id="question_title"></div>
            <div class="mb-3 text required question_description"><label class="form-label text required" for="question_description">Descripción <abbr title="required">*</abbr></label><textarea class="form-control text required" required="required" aria-required="true" name="question[description]" id="question_description"></textarea></div>
              <select class="form-control" required="required" name="question[category]" id="question_category"><option value="">Selecciona una categoría</option>
                <% Category.pluck(:name).each do |name| %>
                  <option value="<%= name %>"><%= name %></option>
                <% end %>
              </select>
              <%# <input type="submit" name="commit" value="Publicar pregunta" class="btn btn btn-flat" data-disable-with="Create Question"> %>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-primary" data-action="click->modal#sendMessage">Confirmar pregunta</button>
              </div>
          </form>
        </div>
      </div>
    </div>
  </div>



  <div class="row mt-5">
    <% current_user.questions.reverse.each do |question| %>
      <div class="col-md-4 mb-4">
        <div class="card-display">
          <div class="card-body">
            <h5 class="card-title"><%= truncate(question.title, length: 65) %></h5>
            <p class="card-text mt-3"><%= truncate(question.description, length: 90) %></p>
          </div>
          <hr>
          <div class="card-footer d-flex justify-content-between align-items-center">
            <%# <%= link_to 'Ver ofertas', question_path(question), class: 'custom-btn btn-1 mr-2' %>
            <%= button_to 'Ver ofertas', question_path(question), method: :get, class:'button-81 mr-2' %>
            <div class="d-flex align-items-center">
              <span class="edit-icon mr-2">
                <%= link_to "#", class: "btn btn-ghost" do %>
                  <i class="fa-regular fa-pen-to-square" type="button" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@mdo" data-controller="modal" data-action="click->modal#openModal"></i>
                  <%# <i class="fa-solid fa-pen"></i> %>
                  <%# <button type="button" class="btn btn-primary"  data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@mdo" data-controller="modal" data-action="click->modal#openModal">Nueva Pregunta</button> %>
                <% end %>
              </span>
              <span class="delete-icon">
                <%= link_to question_path(question.id), data: {turbo_method: :delete}, class: "btn btn-ghost" do %>
                  <i class="fa-regular fa-trash-can"></i> <%# Aca va el destroy action de la question solo si NO fue respondida%>
                  <%# <i class="fa fa-trash fa-sm"></i> %>
                <% end %>
              </span>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<!--
<h1>Mis preguntas</h1>
<%# <p>Find me in app/views/questions/index.html.erb</p> %>

<div class="container">
  <%# <h1 class="text-center">Marketplace</h1> %>
  <button type="button" class="btn btn-primary"  data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@mdo" data-controller="modal" data-action="click->modal#openModal">Nueva Pregunta</button>
  <%# <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@fat" data-controller="modal" data-action="click->modal#openModal">Open modal for @fat</button> %>
  <%# <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@getbootstrap" data-controller="modal" data-action="click->modal#openModal">Open modal for @getbootstrap</button> %>

  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Haz tu pregunta</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%# <form>
            <div class="mb-3">
              <label for="recipient-name" class="col-form-label">Pregunta:</label>
              <input type="text" class="form-control" id="recipient-name">
            </div>
            <div class="mb-3">
              <label for="message-text" class="col-form-label">Contexto:</label>
              <textarea class="form-control" id="message-text"></textarea>
            </div>
          </form> %>
          <form class="simple_form new_question" id="new_question" novalidate="novalidate" action="/questions" accept-charset="UTF-8" method="post"><input type="hidden" name="authenticity_token" value="Xqqv2tmlIS8UdrnikZvjN-zry_0DpGCjSS4OhT9JoZkJwIa-iHW3IwaAbwbYZe8bjY0OyjrRSx0QiK3eS4y2SQ" autocomplete="off">
            <div class="mb-3 string required question_title"><label class="form-label string required" for="question_title">Pregunta <abbr title="required">*</abbr></label><input class="form-control string required" required="required" aria-required="true" type="text" name="question[title]" id="question_title"></div>
            <div class="mb-3 text required question_description"><label class="form-label text required" for="question_description">Descripción <abbr title="required">*</abbr></label><textarea class="form-control text required" required="required" aria-required="true" name="question[description]" id="question_description"></textarea></div>
              <select class="form-control" required="required" name="question[category]" id="question_category"><option value="">Selecciona una categoría</option>
                <% Category.pluck(:name).each do |name| %>
                  <option value="<%= name %>"><%= name %></option>
                <% end %>
              </select>
              <%# <input type="submit" name="commit" value="Publicar pregunta" class="btn btn btn-flat" data-disable-with="Create Question"> %>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-primary" data-action="click->modal#sendMessage">Confirmar pregunta</button>
              </div>
          </form>
        </div>
      </div>
    </div>
  </div>

  <%# <div class="row mt-5"> %>
    <%# <% current_user.questions.each do |question| %>
      <%# <div class="col-md-4 mb-4"> %>
        <%# <div class="card"> %>
          <%# <div class="card-body"> %>
            <%# <h5 class="card-title"><%= question.title</h5> %>
            <%# <p class="card-text"><%= question.description</p> %>
          <%# </div> %>
          <%# <div class="card-footer d-flex justify-content-between align-items-center"> %>
            <%# <%= link_to 'Ver ofertas', question_path(question), class: 'btn btn-primary mr-2' %>
            <%# <div class="d-flex align-items-center"> %>
              <%# <span class="edit-icon mr-2"> %>
                <%# <%= link_to "#", class: "btn btn-ghost" do %>
                  <%# <i class="fa fa-pencil fa-sm"></i> %>
                <%# <% end %>
              <%# </span> %>
              <%# <span class="delete-icon"> %>
                <%# <%= link_to "#", class: "btn btn-ghost" do %>
                  <%# <i class="fa fa-trash fa-sm"></i> %>
                <%# <% end %>
              <%# </span> %>
            <%# </div> %>
          <%# </div> %>
        <%# </div> %>
      <%# </div> %>
    <%# <% end %>
  <%# </div> %>

  <div class="row mt-5">
    <% current_user.questions.each do |question| %>
      <div class="col-md-4 mb-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= truncate(question.title, length: 70) %></h5>
            <p class="card-text"><%= truncate(question.description, length: 100) %></p>
          </div>
          <div class="card-footer d-flex justify-content-between align-items-center">
            <%= link_to 'Ver ofertas', question_path(question), class: 'btn btn-primary mr-2' %>
            <div class="d-flex align-items-center">
              <span class="edit-icon mr-2">
                <%= link_to "#", class: "btn btn-ghost" do %>
                  <i class="fa fa-pencil fa-sm" type="button" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@mdo" data-controller="modal" data-action="click->modal#openModal"></i>
                  <%# <button type="button" class="btn btn-primary"  data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@mdo" data-controller="modal" data-action="click->modal#openModal">Nueva Pregunta</button> %>
                <% end %>
              </span>
              <span class="delete-icon">
                <%= link_to "#", class: "btn btn-ghost" do %>
                  <i class="fa fa-trash fa-sm"></i> <%# Aca va el destroy action de la question solo si NO fue respondida%>
                <% end %>
              </span>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
-->

app/views/questions/new.html.erb
<h1>Questions#new</h1>
<p>Find me in app/views/questions/new.html.erb</p>

app/views/questions/show.html.erb
<div class="container-h1 mt-3">
  <h1><%= @question.title %></h1>
  <h5 class="subtitle"><%= @question.description %></h5>
</div>
<hr>

<div class="container-h1 mt-3">
  <%= button_to "Volver", questions_path, method: :get, class:"button-81" %>
</div>

<div class="container">
  <div class="row mt-3">
    <% @question.answers.each do |answer| %>
    <div class="col-4">
      <div class="card-display mb-5">
        <div class="card-body">
          <div class="d-flex align-items-center justify-content-between">
            <h4 class="card-title">
              <%= answer.user.name %>
            </h4>
            <div class="d-flex align-items-center">
            <% if answer.user.photo.attached? %>
              <%= cl_image_tag answer.user.photo.key, class: "rounded-circle img-thumbnail", width: 50, height: 50 %>
            <% else %>
              <img class="rounded-circle img-thumbnail mb-2" src="https://www.saberescincopuntocero.com/wp-content/uploads/2020/10/PERFIL-VACIO.png", width= 50, height= 50/>
            <% end %>
              <%# <span>User Name</span> %>
            </div>
          </div>
          <p class="card-text mt-3"><%= answer.comment %></p>
          <div class="row">
            <div class="col-6">
              <p>Tiempo estimado de respuesta:
              <br><b><%= answer.avg_time %> hora/s</b></p>
            </div>
            <div class="col-6">
              <span>Precio Final: <b>$<%= answer.price %></b></span>
            </div>
          </div>
          <p class="card-text d-flex align-items-center justify-content-between">
            <span>
              <% if Review.any? %>
                <% count = answer.user.reviews.count %>
                <% sum = answer.user.reviews.sum(:rating) %>
                <% rating = (sum/count.to_f).round(2) %>
                <% black_star = (sum/count).to_i %>
                <% rating.kind_of?(Float) ? half_star = 1 : half_star = 0 %>
                <% white_star = 5 - black_star - half_star %>
                <% black_star.times do %>
                  <i class="fas fa-star"></i>
                <% end %>
                <% half_star.times do %>
                  <i class="fas fa-star-half-alt"></i>
                <% end %>
                <% white_star.times do %>
                  <i class="far fa-star"></i>
                <% end %>
                <%= "(#{rating.round(1)})" %>
              <% else %>
                <% 5.times do %>
                  <i class="far fa-star"></i>
                <% end %>
                <span>(0)</span>
              <% end %>
            </span>
            <hr>
            <%# <%= link_to 'Ver mas', question_answer_path(@question, answer) , class: 'btn btn-primary' %>
            <%= button_to "Ver detalles", question_answer_path(answer.question, answer), method: :get, class: "button-81" %>
          </p>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/questions/update.html.erb
<h1>Questions#update</h1>
<p>Find me in app/views/questions/update.html.erb</p>