config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :questions do
    resources :answers, only: [:create] do
      resources :reviews, only: %i[new create]
      resources :payments, only: %i[new create]
    end
    resources :answers, only: %i[new create show update]
  end
  resources :answers, only: %i[index edit destroy]

  resources :payments, except: [:new, :create]


  post "answers/:id/paid", to: "answers#paid", as: :paid
  get "/questions_lawyers", to: "questions#general", as: :preguntas
  get "answers/:id/response", to: "answers#after_paid", as: :response
  get "answers/:id/choosed", to: "answers#choosed", as: :choosed
  post "answers/:id/procesar-pago", to: "answers#check_payment", as: :check_payment
  #get "pago", to: "answers#pago", as: :pago
  post "process_payment", to: "payments#process_payment"

  resources :users, only: %i[show edit update] do
    resources :studies, only: %i[create update destroy]
    resources :experiences, only: %i[create update destroy]
  end

  get '/404', to: 'errors#not_found'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="container text-center">
    <div class="row">
      <div class="col">
        <img src="https://res.cloudinary.com/dcfoaujd5/image/upload/v1678462895/legalmentor_logo_fqkc2u.svg" alt="" class="logo">
      </div>

    </div>
<!--
    <div class="row mt-3">
      <div class="col">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </div>

      <div class="col">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </div>

      <div class="col">
        <%= link_to "About Us", "#aboutUs", class: "nav-link" %>
      </div>

      <div class="col text-start">
        <p>hola@legalmentor.com</p>
      </div>
    </div>
-->
    <hr>
    <div class="row mt-3">
      <div class="col-2"></div>
      <div class="col-8">
        <p>© 2023 Legal Mentor ❤️ Le wagon 🇨🇱🇦🇷</p>
      </div>
      <div class="col-2"></div>
    </div>

  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/dcfoaujd5/image/upload/v1678462895/legalmentor_logo_fqkc2u.svg" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Responder", preguntas_path, class: "nav-link" %>
          </li>
<%#           <li class="nav-item active">
            <%= link_to "Home",
              if current_user.lawyer
                answers_path
              else
                questions_path
            end, class: "nav-link" %>
         <%# </li> %>
          <%# <li class="nav-item">
            <%= link_to "Consultas", "#", class: "nav-link" %>
         <%# </li> %>
          <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
              <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png"/>
          <% end %>
          <% if current_user.lawyer %>
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                  <%#= link_to "Consultas pendientes", "#", class: "dropdown-item" %>
                  <%= link_to "Mis respuestas", answers_path, class: "dropdown-item" %>
                  <%= link_to "Mi perfil", user_path(current_user), class: "dropdown-item" %>
                  <%= link_to "Cerrar Sesion", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
                </div>
              <% else %>
                 <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                  <%= link_to "Mis consultas", questions_path, class: "dropdown-item" %>
                  <%= link_to "Mi perfil", user_path(current_user), class: "dropdown-item" %>
                  <%= link_to "Cerrar Sesion", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            <% end %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login",  new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>