config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :questions do
    resources :answers, only: [:create] do
      resources :reviews, only: %i[new create]
      resources :payments, only: %i[new create]
    end
    resources :answers, only: %i[new create show update]
  end
  resources :answers, only: %i[index edit destroy]

  resources :payments, except: [:new, :create]


  post "answers/:id/paid", to: "answers#paid", as: :paid
  get "/questions_lawyers", to: "questions#general", as: :preguntas
  get "answers/:id/response", to: "answers#after_paid", as: :response
  get "answers/:id/choosed", to: "answers#choosed", as: :choosed
  post "answers/:id/procesar-pago", to: "answers#check_payment", as: :check_payment
  #get "pago", to: "answers#pago", as: :pago
  post "process_payment", to: "payments#process_payment"

  resources :users, only: %i[show edit update] do
    resources :studies, only: %i[create update destroy]
    resources :experiences, only: %i[create update destroy]
  end

  get '/404', to: 'errors#not_found'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question

  # Response in pdf
  has_one_attached :photo
  has_one :payment


  # Validations
  validates :price, :comment, :avg_time, :payment_status, :user, :question, presence: true

  include AASM

  aasm_column :payment_status
  aasm do
    state :sent, initial: true
    state :accepted, :rejected, :paid, :ended, :discarted

    event :accept do
      transitions from: :sent, to: :accepted
    end

    event :reject do
      transitions from: :sent, to: :rejected
    end

    event :pay do
      transitions from: :accepted, to: :paid
    end

    event :finalize do
      transitions from: :paid, to: :ended
    end

    event :discard do
      transitions from: :sent, to: :discarted
    end
  end
  # waiting, con_respuestas, pagada, respondida, terminada
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_question, only: %i[new create show edit update process check_payment]
  before_action :set_answer, only: %i[show edit update destroy process paid after_paid check_payment choosed]
  def index
    @answers = Answer.all
    # Aca quizas usemos gema cancancan
  end

  def new
    @answer = Answer.new
  end

  def create
    @answer = Answer.new(answer_params)
    @answer.question = @question
    @answer.user = current_user
    @question.new_answer if @question.waiting?
    @question.save
    if @answer.save
      #redirect_to preguntas_path
      redirect_to question_answer_path(@question, @answer)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # def show #cuando apreto el pagar, el boton pagar solo tiene que estar cuando el estado de question es choosing y el de answer es accepted
  #   require 'mercadopago'
  #   # SDK de Mercado Pago
  #   # Agrega credenciales
  #   sdk = Mercadopago::SDK.new('APP_USR-5635626968426827-030609-666b8dcea6c44800593156cf9a9aec97-325153089')

  #   # Crea un objeto de preferencia
  #   preference_data = {
  #     items: [
  #       {
  #         title: @answer.question.title,
  #         unit_price: @answer.price,
  #         quantity: 1
  #       }
  #     ]
  #   }
  #   preference_response = sdk.preference.create(preference_data) # Esto es un post
  #   preference = preference_response[:response] # Esta es la respuesta de mercado pago es un json
  #   @resultado = JSON.parse(preference.to_json)
  #   p @resultado
  #   # Este valor reemplazará el string "<%= @preference_id %>" en tu HTML
  #   @preference_id = preference['id']
  #   @preference_status = preference['status']
  #   # puts "VALORES DE LA API"
  #   # puts "ID: #{@preference_id} STATUS: #{@preference_status}"
  #   #Checkpayment
  # end

  # def check_payment #Para ver si el pago fue exitoso
  #   if @preference_status == "approved"
  #     @answer.pay
  #     @questions.choosed
  #     @answer.save
  #     @question.save
  #   end
  #   redirect_to question_answer_path(@question, @answer)
  # end


  def choosed #Cuando apreto el Contratar
    @answer.accept
    @answer.save
    # raise
    redirect_to new_question_answer_payment_path(@answer.question.id, @answer)
    # rechazar el resto de Answers que habia para esa pregunta TODO
  end

  def after_paid #Cuando tengo que agregar el archivo adjunto
    @question = @answer.question
    @question.answer_delivered
    @question.save
    @answer.finalize
    @answer.save
    redirect_to answer_path(@answer)
  end

  def rejected #Cuando apreto rechazar esa propuesta de respuesta
    @answer.reject
    @answer.save
    redirect_to question_answer_path(@question)
  end

  def edit
  end

  def update
    if @answer.update(answer_params)
      redirect_to question_answer_path(@question, @answer)
    else
      render :edit, status: :unprocessable_entity
    end
  end


  def destroy #si borro la respusta como lawyer
    @answer.destroy
    redirect_to answers_path, status: :see_other
  end


  private

  def answer_params
    params.require(:answer).permit(:price, :payment_status, :comment, :avg_time, :photo, :response_pdf)
  end

  def set_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end
end

app/views/answers/_form.html.erb
<%= simple_form_for [@question, @answer] do |f| %>
  <%= f.input :price, label: "$CLP Precio Final", required: true %>
  <%= f.input :comment, label: "¿Por qué eres el indicado?", required: true %>
  <%= f.input :avg_time, label: "Tiempo (horas) estimado de respuesta:", required: true %>
  <%= f.button :submit, class: "success-btn", value:"Proponer" %>
<% end %>

app/views/answers/_review_form.html.erb
<%= form_with(url: question_answer_path, method: :post, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :rating %>
    <%= form.select :rating, (1..5).to_a, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :comment %>
    <%= form.text_area :comment, class: 'form-control' %>
  </div>
  <%= form.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

app/views/answers/create.html.erb
<h1>Answers#create</h1>
<p>Find me in app/views/answers/create.html.erb</p>

app/views/answers/destroy.html.erb
<h1>Answers#destroy</h1>
<p>Find me in app/views/answers/destroy.html.erb</p>

app/views/answers/edit.html.erb
<h1>Answers#edit</h1>
<p>Find me in app/views/answers/edit.html.erb</p>

app/views/answers/index.html.erb
<div class="container-h1 mt-3">
  <h1>Mis respuestas</h1>
</div>
<hr>
<div class="container mt-3">
    <%= button_to "Buscar nuevas preguntas", preguntas_path, method: :get, class:"button-79" %>
</div>

<%# <p>Find me in app/views/answers/index.html.erb</p> %>

  <div class="row mt-5">
    <% current_user.answers.reverse.each do |answer| %>
      <div class="col-md-4 mb-4">
        <div class="card-display">
          <div class="card-body">
            <h5 class="card-title"><%= truncate(answer.question.title, length: 50) %></h5>
            <p class="card-text"><%= truncate(answer.comment, length: 70) %></p>
            <hr>
            <%# <%= link_to 'View details', question_answer_path(answer.question, answer), class: 'button-81'%>
            <%= button_to "Ver detalles", question_answer_path(answer.question, answer), method: :get, class: "button-81" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/answers/new.html.erb
<div class="container-h1 mt-3">
  <h1>Formula tu propuesta:</h1>
</div>
<hr>
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="card-comment">
        <div class="card-body">
          <%= render "form" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/answers/paid.html.erb
// SDK MercadoPago.js
<script src="https://sdk.mercadopago.com/js/v2"></script>


<div class="cho-container"></div>
<script>
  const mp = new MercadoPago('PUBLIC_KEY', {
    locale: 'es-AR'
  });

  mp.checkout({
    preference: {
      id: @preference.id,,
    },
    render: {
      container: '.cho-container',
      label: 'Pagar',
    }
  });
</script>
<%  %>

app/views/answers/show.html.erb
<div class="container-h1 mt-4">
  <h1><%= @question.title %></h1>
  <h5 class="subtitle"><%= @question.description %></h5>
</div>
<hr>

<% if current_user.lawyer? %>
  <div class="container-h1 mt-3">
    <%= button_to "Volver", answers_path, method: :get, class:"button-81" %>
  </div>
<% else %>
  <div class="container-h1 mt-3">
    <%= button_to "Volver", question_path(@question), method: :get, class:"button-81" %>
  </div>
<% end %>


<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="card-comment">
        <div class="card-body">
            <div class="container d-flex justify-content-center">
            <div class="row">
              <div class="col-12 text-center">
                <%= link_to user_path(@answer.user), style: "text-decoration:none; color:inherit;" do %>
                        <% if @answer.user.photo.attached? %>
                          <%= cl_image_tag @answer.user.photo.key, class: "rounded-circle img-thumbnail", width: 150, height: 150 %>
                        <% else %>
                          <img class="rounded-circle img-thumbnail mb-2" src="https://www.saberescincopuntocero.com/wp-content/uploads/2020/10/PERFIL-VACIO.png", width= 150, height= 150/>
                        <% end %>
                  <h4 class="card-title">
                      <%= @answer.user.name%> <%= @answer.user.last_name  %>
                  </h4>
                <% end %>
                  <div class="mt-1">
                    <%# <span> %>
                      <%# <% if Review.any? %>
                        <%# <%= star_rating(Review.average(:rating).round(1)) %>
                      <%# <% else %>
                        <%# <%= star_rating(0) %>
                      <%# <% end %>
                    <%# </span> %>
                    <span>
                      <% if Review.any? %>
                        <% count = @answer.user.reviews.count %>
                        <% sum = @answer.user.reviews.sum(:rating) %>
                        <% rating = (sum/count.to_f).round(2) %>
                        <% black_star = (sum/count).to_i %>
                        <% rating.kind_of?(Float) ? half_star = 1 : half_star = 0 %>
                        <% white_star = 5 - black_star - half_star %>
                        <% black_star.times do %>
                          <i class="fas fa-star"></i>
                        <% end %>
                        <% half_star.times do %>
                          <i class="fas fa-star-half-alt"></i>
                        <% end %>
                        <% white_star.times do %>
                          <i class="far fa-star"></i>
                        <% end %>
                        <%= "(#{rating.round(1)})" %>
                      <% else %>
                        <% 5.times do %>
                          <i class="far fa-star"></i>
                        <% end %>
                        <span>(0)</span>
                      <% end %>
                    </span>
                  </div>
                  <p class="card-text mt-4">
                    <span class="mr-3">Tiempo de respuesta estimado: <b><%= @answer.avg_time %></b></span>
                  </p>
                  <p class="card-text">
                    <span class="mr-3">Precio Final: <b>$ <%= @answer.price %></b></span>
                  </p>
              </div>
            </div>
          </div>
          <hr>
          <h4 class="mt-5">Oferta:</h4>
          <p><%= @answer.comment %></p>
          <%# 1 %>
          <% if @question.choosing? && @answer.sent? && current_user == @question.user%>
            <div class= "d-flex justify-content-between align-items-center">
              <%#= button_to "Volver", question_path(@question), method: :get %>
              <%= button_to "Contratar", choosed_path(@answer), method: :get, class:"success-btn" %>
            </div>
          <% end %>
          <%# 3 %>
          <% if @question.paid? && @answer.paid? && current_user == @answer.user %>
          <%# Este es el form para adjuntar un archivo a la respuesta %>
            <div class="container">
              <%= simple_form_for([@question, @answer], html: { method: :put }) do |f| %>
                <%= f.error_notification %>
                <div class="form-inputs">
                  <%= f.input :photo, label: "Adjunta tu respuesta en formato pdf, jpg, png", as: :file %>
                </div>
                <div class="form-actions">
                  <%= f.button :submit, "Agregar", class: "enviar-btn" %>
                </div>
              <% end %>

                <%# <h3> Previsualización:</h3> %>
              <%# Este es el preview %>
              <%#= cl_image_tag "#{@answer.photo.key}.png", :width=>600, :height=>700 %>
              <% if @answer.photo.attached? %>
                <%#= cl_image_tag @answer.photo.key, :width=>600, :height=>700 %>
                <h4 class="mt-5">Preview:</h4>
                <%= cl_image_tag "#{@answer.photo.key}.jpg", :width=>600, :height=>700, :page=>1, :crop=>"fill"%>
              <% end %>
              <p> </p>
              <%= button_to "Enviar respuesta", response_path(@answer), method: :get, class:"button-81", :target=>'_blank' %>

            </div>
          <% end %>
          <%# 4 %>
          <% if @question.answered? && @answer.ended? && current_user == @question.user%>
            <%= button_to "Dejar Review", new_question_answer_review_path(@question, @answer), method: :get, class:"success-btn" %>
            <%#= link_to "Descargar Documento", cl_image_path(@answer.photo.key, resource_type: :image, type: :upload) %>
            <%#= button_to "Descargar Documento", cl_image_path(@answer.photo.key, resource_type: :image, type: :upload), method: :get, class:"button-81 btn-lg" %>
            <%= link_to "Descargar Documento", cl_image_path(@answer.photo.key, resource_type: :image, type: :upload), class:"button-82 btn-lg border border-secondary", target: "_blank" %>
          <% end %>
          <% case @answer.payment_status %>
          <% when "sent" %>
            <h6 class="text-end ms-3 mt-3">Estado: <span class="label label-green">Enviado</span></h6>
          <% when "accepted" %>
            <h6 class="text-end ms-3 mt-3">Estado: <span class="label label-green">Respuesta aceptada</span></h6>
          <% when "paid" %>
            <h6 class="text-end ms-3 mt-3">Estado: <span class="label label-green">Respuesta abonada</span></h6>
          <% when "ended" %>
            <h6 class="text-end ms-3 mt-3">Estado: <span class="label label-green">Consulta finalizada</span></h6>
          <% else %>
            <h6 class="text-end ms-3 mt-3">Estado: <span class="label label-green">Respuesta rechazada</span></h6>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>





<!--
Instrucciones sobre botones PARA USER con condiciones:
1:
  2 botones uno para volver y otro para contratar.
  Condicion: Solo puede aparecer si se cumple question.choosing && answer.sent
2:
  -Se oculta el boton volver y contratar
  -Se muestra boton Pagar.
  Condicion: Si se cumple question.choosing && answer.accepted
3:
  -Se oculta el pagar, y aparece SOLO PARA LAWYER el submit para adjuntar pdf
  condicion: question.paid && answer.paid && current.user.lawyer
4:
  -Aparecen botones para descargar solucion y para dejar review.
  condicion: question.answered && answer.ended
-->

<!--
<%# 2 %>
<% if @question.choosing? && @answer.accepted? && current_user == @question.user %>
<%# Este form es el boton pagar de mercado pago! %>
  <script src="https://www.mercadopago.cl/integrations/v1/web-payment-checkout.js" data-preference-id="<%= @preference_id %>">
  </script>
  <script>
  // Listen for the "payment.created" event
  window.addEventListener("payment.created", function(event) {
    // Save the payment response to your backend
    const paymentResponse = event.detail;
    fetch('/answers/<%= @answer.id %>/procesar-pago', {
      method: 'POST',
      body: JSON.stringify(paymentResponse),
      headers: {
        'Content-Type': 'application/json'
      }
    })
    .then(response => {
      console.log('Payment response saved successfully.');
    })
    .catch(error => {
      console.error('Error saving payment response:', error);
    });
  });
  </script>
  -->
<!--

  <form action="/answers/<%=@answer.id%>/procesar-pago" method="POST">
      <script src="https://www.mercadopago.cl/integrations/v1/web-payment-checkout.js" data-preference-id="<%= @preference_id %>">
      </script>
  </form>
<% end %>



<%# 3 %>
<% if @question.paid? && @answer.paid? && current_user == @answer.user %>
<%# Este es el form para adjuntar un archivo a la respuesta %>
  <div class="container">
    <%= simple_form_for([@question, @answer], html: { method: :put }) do |f| %>
      <%= f.error_notification %>
      <div class="form-inputs">
        <%= f.input :photo, label: "Adjunta tu respuesta en formato pdf, jpg, png", as: :file %>
      </div>
      <div class="form-actions">
        <%= f.button :submit, "Agregar", class: "btn btn-primary btn-lg" %>
      </div>
    <% end %>

      <%# <h3> Previsualización:</h3> %>
    <%# Este es el preview %>
    <%#= cl_image_tag "#{@answer.photo.key}.png", :width=>600, :height=>700 %>
    <% if @answer.photo.attached? %>
      <%#= cl_image_tag @answer.photo.key, :width=>600, :height=>700 %>
      <h3> Preview: </h3>
      <%= cl_image_tag "#{@answer.photo.key}.jpg", :width=>600, :height=>700, :page=>1, :crop=>"fill"%>
    <% end %>

    <%= button_to "Enviar respuesta", response_path(@answer), method: :get %>

  </div>
<% end %>

<%# 4 %>
<% if @question.answered? && @answer.ended? && current_user == @question.user%>
  <p>Dejar review y descargar</p>
  <%#= link_to "Descargar Documento", cl_image_path(@answer.photo.key, resource_type: :image, type: :upload) %>
  <%= button_to "Descargar Documento", cl_image_path(@answer.photo.key, resource_type: :image, type: :upload), method: :get, class:"button-81 btn-lg"  %>
<% end %>

  <%#= cl_image_tag "#{@answer.photo.key}.jpg", :width=>700, :height=>700, :page=>2, :crop=>"fill" %>
  <%#= cl_video_tag @answer.photo.key, resource_type: :image, format: 'pdf' %>
  <%#= cl_image_tag "#{@answer.photo.key}.jpg", pages: "1-3" %>


  <%#= cl_image_tag("https://res.cloudinary.com/dcfoaujd5/image/fetch/w_800,h_600,c_fill,g_auto,q_auto,f_auto/page_1/#{@answer.photo.key}", alt: "PDF thumbnail") %>
  <%#= cl_video_tag("https://res.cloudinary.com/dcfoaujd5/video/upload/fl_attachment/v1/#{@answer.photo.key}.pdf", resource_type: :video, alt: "PDF document") %>
<%# ANSWER VIEW %>
<!-- DESCOMENTAR PARA TRABJAR EN FRONT

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1 class="text-left"><%= @question.title %></h1>
      <div class="d-flex justify-content-between align-items-center">
        <div class="d-flex align-items-center">
          <img src="https://via.placeholder.com/150" class="rounded-circle mr-3" alt="Lawyer Avatar">
          <div>
            <h5 class="mb-2"><%= @answer.user.name %></h5>
            <div class="d-flex align-items-center">
              <p class="mb-2">Rating: </p>
              <i class="fa fa-star text-warning"></i>
              <p class="mb-2"><b>4.5</b></p>
            </div>
            <p class="mb-2">Avg time of answer: <b>2 hours</b></p>
            <p class="mb-2">Price: <b>$50</b></p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body">
          <p class="card-text">Description or comment of the lawyer explaining why he is capable of responding to the question.</p>
        </div>
      </div>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-md-12">
      <div class="d-flex justify-content-between align-items-center mt-4 mx-2">
        <button class="btn btn-danger mr-3">Rechazar</button>
        <button class="btn btn-success">Aceptar</button>
      </div>
    </div>
  </div>

  <%# <button type="button" class="btn btn-primary"  data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@mdo" data-controller="modal" data-action="click->modal#openModal">Nueva Pregunta</button> %>
  <button type="button" class="btn btn-primary"  data-bs-toggle="modal" data-bs-target="#exampleReview" data-bs-whatever="@mdo" data-controller="reviews" data-action="click->reviews#showModal">Dejanos tu Reseña</button>

  <%# <%= link_to 'Leave your Review', '#', class: 'btn btn-primary', data: { action: 'click->reviews#showModal' } %>
  <%# <%= button_to 'Leave your Review', class: 'btn btn-primary', data: { action: 'click->reviews#showModal',  } %>
  <div class="modal fade" data-controller="reviews" id="exampleReview" aria-labelledby="exampleReviewLabel">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Leave your Review</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close" data-action="click->reviews#hideModal">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= render partial: 'review_form' %>
        </div>
      </div>
    </div>
  </div>
</div>
-->

app/views/answers/update.html.erb
<h1>Answers#update</h1>
<p>Find me in app/views/answers/update.html.erb</p>