config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :questions do
    resources :answers, only: [:create] do
      resources :reviews, only: %i[new create]
      resources :payments, only: %i[new create]
    end
    resources :answers, only: %i[new create show update]
  end
  resources :answers, only: %i[index edit destroy]

  resources :payments, except: [:new, :create]


  post "answers/:id/paid", to: "answers#paid", as: :paid
  get "/questions_lawyers", to: "questions#general", as: :preguntas
  get "answers/:id/response", to: "answers#after_paid", as: :response
  get "answers/:id/choosed", to: "answers#choosed", as: :choosed
  post "answers/:id/procesar-pago", to: "answers#check_payment", as: :check_payment
  #get "pago", to: "answers#pago", as: :pago
  post "process_payment", to: "payments#process_payment"

  resources :users, only: %i[show edit update] do
    resources :studies, only: %i[create update destroy]
    resources :experiences, only: %i[create update destroy]
  end

  get '/404', to: 'errors#not_found'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_answer, only: %i[new create]
  before_action :set_question, only: %i[new create]
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(params_review)
    @user_lawyer = @answer[:user_id]
    @review.user = User.find(@user_lawyer)
    if @review.save
      redirect_to questions_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def params_review
    params.require(:review).permit(:rating, :comment)
  end

  def set_answer
    @answer = Answer.find(params[:answer_id])
  end

  def set_question
    @question = Question.find(params[:question_id])
  end
end

app/views/reviews/_reviews_form.html.erb
<%# <%= simple_form_for [@question, @answer, @review] do |f| %>
  <%# <%= f.input :rating, label: "Rating:", required: true %>
  <%# <%= f.input :comment, label: "Comentario", required: false %>
  <%# <%= f.button :submit, class: "success-btn", value:"Finalizar" %>
<%# <% end %>

<%= simple_form_for [@question, @answer, @review] do |f| %>
  <%= f.input :rating, label: "Rating:", required: true, collection: [[1, "1"], [2, "2"], [3, "3"], [4, "4"], [5, "5"]], input_html: { class: 'form-control' } %>
  <%= f.input :comment, label: "Comentario", required: false %>
  <%= f.button :submit, class: "success-btn", value:"Finalizar" %>
<% end %>

app/views/reviews/new.html.erb
<% if current_user.lawyer? %>
    <div class="h-100 d-flex align-items-center justify-content-center opacity-75" style="margin-top: 20px;">
      <br>
      <h2> Esta sección es solo para usuarios </h2>
    </div>
    <div class="h-100 d-flex align-items-center justify-content-center" style="margin-top: 10px; ">
    <%= button_to "Volver", answers_path, method: :get, class:"button-81" %>
  </div>
<% else %>
  <div class="container-h1 mt-3">
    <h1>Deja una reseña para el abogado</h1>
  </div>
  <hr>
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="card-comment">
          <div class="card-body">
            <%= render "reviews_form" %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>